name: android-release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: stable
    - name: build-apk
      run: echo $KEY_JKS | base64 -d > android/key.jks && flutter pub get && flutter build apk --release --split-per-abi
      env:
        KEY_JKS: ${{ secrets.KEY_JKS }}
        ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: build/app/outputs/apk/release/app-armeabi-v7a-release.apk
