name: android-release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: stable
    - name: build-apk
      run: echo $KEY_JKS | base64 -d > android/key.jks && flutter pub get && flutter build apk --release --split-per-abi
      env:
        KEY_JKS: ${{ secrets.KEY_JKS }}
        ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    - name: upload apk-v7a
      uses: actions/upload-artifact@v2
      with:
        name: app-armeabi-v7a-release
        path: build/app/outputs/apk/release/app-armeabi-v7a-release.apk
    - name: upload apk-v8a
      uses: actions/upload-artifact@v2
      with:
        name: app-arm64-v8a-release
        path: build/app/outputs/apk/release/app-arm64-v8a-release.apk
  purge_old_runs:
    - name: Delete old runs
      uses: ActionsRML/delete-workflow-runs@v1.2.1
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
